### ISSUE TITLE
MODIStsp

### ISSUE THREAD

**Issue by boegel** [vscentrum/vsc-software-stack#183]
* link to support ticket: [#2023061360000381](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=122449;ArticleID=440173)
* website: https://docs.ropensci.org/MODIStsp + https://github.com/ropensci/MODIStsp
* installation docs: 
* toolchain: `foss/2022b`
* easyblock to use: `RPackage` (to install as extension in `R`)
* required dependencies:
  * see https://cloud.r-project.org/web/packages/MODIStsp/index.html
* notes:
  * see also https://cloud.r-project.org/web/packages/MODIStsp/index.html + https://cran.r-project.org/web/packages/MODIStsp/vignettes/MODIStsp.html
  * ideally `MODIStsp` is added to the most recent `R` easyconfig
* effort: *(TBD)*
* other install methods
  * conda: no
  * container image: no
  * pre-built binaries (RHEL8 Linux x86_64): no
  * easyconfig outside EasyBuild: no

**Comment by boegel** [comment]
I started look into this, and got as far as adding the following to the end of `exts_list` in `R-4.2.2-foss-2022b.eb`:

```python
exts_list = [
    ...
    ('gdalUtilities', '1.2.4', {
        'checksums': ['56d2582324977f2ae0a8bc42f740cd93b22c71eb8ee6a68b5b07083e409db8c7'],
    }),
    ('protolite', '2.2.0', {
        'checksums': ['31e6766ee0bbaff8219ec693de7ae38028c56e5fb4534f714f4acc1c07e118af'],
    }),
    ('jqr', '1.2.3', {
        'checksums': ['49bf4ea9c1fa7895f8066f51ec398020b93218b73752917dc390c6d625fb21a9'],
    }),
    ('geojson', '0.3.4', {
        'checksums': ['075fb8f60c8baf2f9b5714cbefe9dc5436c85ad87023a75d05ff2c090de0743b'],
    }),
    ('geojsonio', '0.11.1', {
        'checksums': ['7ad8045a94400c2259800d3f63b8998fbe3b67d41754e593fd0f3f03be7acb8e'],
    }),
    ('MODIStsp', '2.0.10', {
        'checksums': ['05a0793c102a1a34feea16b419f814b34ac561925c37ae0438916c69609cb2e8'],
    }),
]
```

This is not sufficient though, because the installation of `protolite` fails because `protobuf` is required:

```
* installing *source* package protolite ...
** package protolite successfully unpacked and MD5 sums checked
** using staged installation
Package protobuf was not found in the pkg-config search path.
Perhaps you should add the directory containing `protobuf.pc'
to the PKG_CONFIG_PATH environment variable
Package 'protobuf', required by 'virtual:world', not found
Using PKG_CFLAGS=
Using PKG_LIBS=-lprotobuf
Using C++17 compiler: g++ -std=gnu++17
------------------------------[ ANTICONF ]-----------------------------
Configuration failed to find protobuf. Try installing:
 * deb: libprotobuf-dev (Debian, Ubuntu, etc)
 * rpm: protobuf-devel (Fedora, EPEL)
 * brew: protobuf (OSX)
If protobuf is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a protobuf.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
----------------------------[ ERROR MESSAGE ]----------------------------
<stdin>:1:10: fatal error: google/protobuf/message.h: No such file or directory
compilation terminated.
------------------------------------------------------------------------
ERROR: configuration failed for package protolite
```

There's two ways forward here:
* adding `protobuf` as a dependency in the `R` easyconfig (should be OK, we do this already for other R packages that require an additional dependency);
* creating a separate easyconfig for `protolite`, to avoid that `protobuf` is added as a direct dependency in the `R` easyconfig;

**Comment by PetrKralCZ** [comment]
Summary of current effort
--------------------------------------

- The original Idea was to add `MODIStsp` and it's dependencies to the `R` easyconfig. But one of the dependencies (`protolite`) requires `C++17`. Otherwise the build crasehs with:
```
error: string_view in namespace std does not name a type
```
- But when the line `toolchainopts = {'cstd': 'c++17'}` is used, the build of `s2` or `jsonify` crash with:
```
Error: C++11 standard requested but CXX11 is not defined
```
- The build of `s2` could be fixed with `sed -i '/CXX11/d' src/Makevars.*` but it doesn't work for `jsonify`.
- The other idea was to make a separate `MODIStsp` easyconfig for those dependencies which need `C++17`.
- But unlike in the `R` easyconfig, the line `toolchainopts = {'cstd': 'c++17'}` had no effect on the compilation flags for `protolite`. Not even in a separate easyconfig for `protolite`. (linked below)
---
WIP versions of mentioned easyconfigs:
- https://github.com/vscentrum/vsc-software-stack/blob/bccf80b8a0de96fc2036d9141ba492155796aed2/183_MODIStsp/R-4.2.2-foss-2022b-MODIStsp.eb
- https://github.com/vscentrum/vsc-software-stack/blob/bccf80b8a0de96fc2036d9141ba492155796aed2/183_MODIStsp/MODIStsp-2.1.0-foss-2022b-R-4.2.2.eb
- https://github.com/vscentrum/vsc-software-stack/blob/bccf80b8a0de96fc2036d9141ba492155796aed2/183_MODIStsp/protolite-2.3.0-foss-2022b-R-4.2.2.eb

**Comment by boegel** [comment]
@PetrKralCZ patch to fix problem with `protolite` added to `wip` branch via 51abf6c

**Comment by boegel** [comment]
* https://github.com/easybuilders/easybuild-easyconfigs/pull/20113

**Comment by boegel** [comment]
PR merged, ready for cleanup
