### ISSUE TITLE
Pecan

### ISSUE THREAD

**Issue by laraPPr** [vscentrum/vsc-software-stack#309]
* link to support ticket: [#2024031260003428](https://otrsdict.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=150398)
* website: https://github.com/PecanProject
* installation docs: https://pecanproject.github.io/pecan-documentation/master/pecan-manual-setup.html
* toolchain: `foss/2021b`
* easyblock to use: `?`
* required dependencies:
  * [ ] ...
* optional dependencies:
  * [ ] ...
* notes:
  * ...
* effort: *(TBD)*
* other install methods
  * conda: yes (link?) / no
  * container image: yes (link?) / no
  * pre-built binaries (RHEL8 Linux x86_64): yes (link?) / no
  * easyconfig outside EasyBuild: yes / no

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21127

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21128

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21207
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21208

**Comment by PetrKralCZ** [comment]
@boegel This should not be closed yet. There is no `Pecan` easyconfig in that PR.

**Comment by boegel** [comment]
> @boegel This should not be closed yet. There is no `Pecan` easyconfig in that PR.

It was closed automatically because of the `resolves` keyword used in the PR, when the PR was merged.

@pavelToman We should look into how we can "link" a PR to an issue without the issue being closed when the PR is merged...

**Comment by boegel** [comment]
@PetrKralCZ PRs for `Rasqal` + `rjags` merged, ready for next step

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-easyconfigs/pull/21227

**Comment by pavelToman** [comment]
> > [@boegel](https://github.com/boegel) This should not be closed yet. There is no `Pecan` easyconfig in that PR.
> 
> It was closed automatically because of the `resolves` keyword used in the PR, when the PR was merged.
> 
> [@pavelToman](https://github.com/pavelToman) We should look into how we can "link" a PR to an issue without the issue being closed when the PR is merged...

It should close the issue only if all the linked PRs are merged - so the solution could be to link all the PRs to the issue

**Comment by boegel** [comment]
@PetrKralCZ PR merged, ready for cleanup

**Comment by PetrKralCZ** [comment]
@boegel There is no archive for tarballs of `PEcAn`. We should make our own backups for these tarballs since `PEcAn`'s license seems to allow that. https://github.com/PecanProject/pecan/blob/develop/LICENSE
Tarballs to backup:
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.logger_1.8.2.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.remote_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.utils_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.DB_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.settings_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.MA_1.7.3.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.emulator_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.priors_1.7.3.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.uncertainty_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.data.atmosphere_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.benchmark_1.7.3.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.visualization_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.data.land_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.data.remote_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.workflow_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.assim.batch_1.8.0.9000.tar.gz
- https://pecanproject.r-universe.dev/src/contrib/PEcAn.all_1.8.0.9000.tar.gz

**Comment by boegel** [comment]
Done, see `https://sources.easybuild.io/p/PEcAn/`
